name: argus

services:
  redpanda:
    image: redpandadata/redpanda:v24.2.7
    command:
      - redpanda
      - start
      - --mode=dev-container
      - --smp=1
      - --default-log-level=warn
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -q 'Healthy:.*true'"]
      interval: 10s
      timeout: 5s
      retries: 12

  console:
    image: redpandadata/console:v2.7.2
    depends_on:
      - redpanda
    ports:
      - "8081:8080"
    environment:
      KAFKA_BROKERS: redpanda:9092

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: argus
      POSTGRES_PASSWORD: argus
      POSTGRES_DB: argus
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U argus"]
      interval: 5s
      timeout: 3s
      retries: 12

  transactions-api:
    build:
      context: .
      dockerfile: src/Argus.Transactions/Dockerfile
    depends_on:
      redpanda:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=argus;Username=argus;Password=argus"
      Kafka__BootstrapServers: "redpanda:9092"
    ports:
      - "8080:8080"

  fraud-worker:
    build:
      context: .
      dockerfile: src/Argus.FraudWorker/Dockerfile
    depends_on:
      redpanda:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=argus;Username=argus;Password=argus"
      Kafka__BootstrapServers: "redpanda:9092"

  notifications:
    build:
      context: .
      dockerfile: src/Argus.Notifications/Dockerfile
    depends_on:
      redpanda:
        condition: service_healthy
    environment:
      Kafka__BootstrapServers: "redpanda:9092"
